# Generated by Django 3.2.25 on 2024-07-04 09:44

from django.db import migrations, models
import log_tracker.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10, validators=[log_tracker.validators.validate_log_level])),
                ('log_date_time', models.DateTimeField()),
                ('message', models.CharField(blank=True, max_length=4096)),
            ],
        ),
    ]
